import { readFile as fsReadFile, mkdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Script } from "./types.js";

// ─── Public types ─────────────────────────────────────────────────────────────

/** A single group entry from scripts/groups.json */
export interface GroupEntry {
	/** Unique group ID, e.g. "linux-dev-setup" */
	id: string;
	/** Human-readable display name */
	name: string;
	/** One-line description shown on browse + detail pages */
	description: string;
}

/** Injectable dependencies for loadGroups — allows unit tests to supply in-memory fixtures */
export interface LoadGroupsDeps {
	/** Reads a file by path and returns its text contents */
	readFile: (path: string) => Promise<string>;
	/** Writes content to the given path (creates the file) */
	writeFile: (path: string, content: string) => Promise<void>;
	/** Absolute path to the groups.json manifest file */
	groupsFilePath: string;
	/** Absolute path to the scripts root directory (repo-root scripts/) */
	scriptsRootPath: string;
}

// ─── Constants ────────────────────────────────────────────────────────────────

const RAW_BASE =
	"https://raw.githubusercontent.com/beolson/Scriptor/main/scripts";

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Read a file as text. Uses Bun.file() when available, falls back to node:fs */
function readFileCompat(path: string): Promise<string> {
	if (typeof Bun !== "undefined") {
		return Bun.file(path).text();
	}
	return fsReadFile(path, "utf8");
}

/** Write content to a file path. Uses Bun.write() when available, falls back to node:fs */
async function writeFileCompat(path: string, content: string): Promise<void> {
	if (typeof Bun !== "undefined") {
		await Bun.write(path, content);
	} else {
		const { writeFile: fsWriteFile } = await import("node:fs/promises");
		await fsWriteFile(path, content, "utf8");
	}
}

/**
 * Type guard: check that a value is a non-null object with string id, name, description.
 */
function isGroupEntry(value: unknown): value is GroupEntry {
	if (typeof value !== "object" || value === null) return false;
	const obj = value as Record<string, unknown>;
	return (
		typeof obj.id === "string" &&
		obj.id.length > 0 &&
		typeof obj.name === "string" &&
		obj.name.length > 0 &&
		typeof obj.description === "string" &&
		obj.description.length > 0
	);
}

/**
 * Sort comparator for group members: ascending by groupOrder (undefined last),
 * then by id as tiebreaker.
 */
function compareMemberScripts(a: Script, b: Script): number {
	const aOrder = a.groupOrder ?? Number.POSITIVE_INFINITY;
	const bOrder = b.groupOrder ?? Number.POSITIVE_INFINITY;
	if (aOrder !== bOrder) return aOrder - bOrder;
	return a.id.localeCompare(b.id);
}

/**
 * Extract the platform prefix (first path segment) from a script id.
 * e.g. "linux/ubuntu-24.04-x64/install-bun" → "linux"
 */
function platformPrefixFromId(id: string): string {
	return id.split("/")[0] ?? id;
}

/**
 * Extract the raw script URL from a script's runCommand.
 * For .sh: "curl -fsSL <url> | bash" → <url>
 * For .ps1: "irm <url> | iex" → <url>
 * Falls back to constructing from RAW_BASE + id if parsing fails.
 */
function rawUrlFromScript(script: Script): string {
	// Try to parse the URL from runCommand
	const shMatch = script.runCommand.match(/curl -fsSL\s+(\S+)\s+\|/);
	if (shMatch) return shMatch[1];
	const ps1Match = script.runCommand.match(/irm\s+(\S+)\s+\|/);
	if (ps1Match) return ps1Match[1];
	// Fallback: construct from id (assume .sh)
	return `${RAW_BASE}/${script.id}.sh`;
}

/** Determine the file extension for a runner script based on the platform of its members */
function runnerExtension(member: Script): ".sh" | ".ps1" {
	// If runCommand uses irm/iex, it's PowerShell
	if (member.runCommand.startsWith("irm ")) return ".ps1";
	return ".sh";
}

/**
 * Build the bash runner script for a group.
 */
function buildBashRunner(group: GroupEntry, members: Script[]): string {
	const total = members.length;
	const steps = members.map((m, i) => {
		const url = rawUrlFromScript(m);
		const n = i + 1;
		return `echo "[${n}/${total}] ${m.title}..."\ncurl -fsSL "${url}" | bash`;
	});
	return [
		"#!/bin/bash",
		"set -euo pipefail",
		"",
		`# Runner script for group: ${group.name}`,
		`# Generated by Scriptor — do not edit by hand.`,
		"",
		...steps,
		"",
		`echo "All ${total} script(s) complete."`,
	].join("\n");
}

/**
 * Build the PowerShell runner script for a group.
 */
function buildPs1Runner(group: GroupEntry, members: Script[]): string {
	const total = members.length;
	const steps = members.map((m, i) => {
		const url = rawUrlFromScript(m);
		const n = i + 1;
		return `Write-Host "[${n}/${total}] ${m.title}..."\nirm "${url}" | iex`;
	});
	return [
		"<#",
		`Runner script for group: ${group.name}`,
		"Generated by Scriptor — do not edit by hand.",
		"#>",
		"",
		'$ErrorActionPreference = "Stop"',
		"",
		...steps,
		"",
		`Write-Host "All ${total} script(s) complete."`,
	].join("\n");
}

// ─── Default deps ─────────────────────────────────────────────────────────────

// Navigate from lib/ → scriptor-web/ → 20_Applications/ → repo root
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");

// Allow SCRIPTS_DIR env var to override the default scripts/ folder
const defaultScriptsDir = process.env.SCRIPTS_DIR
	? resolve(repoRoot, process.env.SCRIPTS_DIR)
	: resolve(repoRoot, "scripts");

const defaultGroupsFilePath = resolve(defaultScriptsDir, "groups.json");

const defaultDeps: LoadGroupsDeps = {
	readFile: readFileCompat,
	writeFile: async (path: string, content: string) => {
		// Ensure parent directory exists before writing
		await mkdir(dirname(path), { recursive: true });
		await writeFileCompat(path, content);
	},
	groupsFilePath: defaultGroupsFilePath,
	scriptsRootPath: defaultScriptsDir,
};

// ─── loadGroups ───────────────────────────────────────────────────────────────

/**
 * Reads scripts/groups.json, parses the manifest, validates entries, and returns
 * a GroupEntry[].
 *
 * Side effect: for each group with at least one valid member, writes the ordered
 * runner script to scripts/<platform-prefix>/<group-id>/run-all.{sh,ps1}.
 *
 * Error handling:
 * - Returns [] and console.warn on missing or malformed groups.json — never throws on I/O
 * - Throws a hard Error if a group's members span multiple platforms (build failure)
 * - Warns and skips runner generation when a group has no valid members
 * - Warns when a script's group field references an unknown group ID
 *
 * Pass `deps` to override filesystem behaviour in unit tests.
 */
export async function loadGroups(
	scripts: Script[],
	deps?: Partial<LoadGroupsDeps>,
): Promise<GroupEntry[]> {
	const { readFile, writeFile, groupsFilePath, scriptsRootPath } = {
		...defaultDeps,
		...deps,
	};

	// ── 1. Read and parse groups.json ──────────────────────────────────────────
	let rawEntries: unknown[];
	try {
		const text = await readFile(groupsFilePath);
		const parsed = JSON.parse(text);
		if (!Array.isArray(parsed)) {
			console.warn(
				"[loadGroups] groups.json top-level value is not an array — returning []",
			);
			return [];
		}
		rawEntries = parsed;
	} catch (err) {
		console.warn(
			`[loadGroups] Could not read or parse groups.json: ${(err as Error).message}`,
		);
		return [];
	}

	// ── 2. Validate entries ────────────────────────────────────────────────────
	const groups: GroupEntry[] = rawEntries.filter((entry): entry is GroupEntry =>
		isGroupEntry(entry),
	);
	const groupIdSet = new Set(groups.map((g) => g.id));

	// ── 3. Warn about scripts that reference unknown group IDs ─────────────────
	const unknownGroupIds = new Set<string>();
	for (const script of scripts) {
		if (
			script.group !== undefined &&
			!groupIdSet.has(script.group) &&
			!unknownGroupIds.has(script.group)
		) {
			unknownGroupIds.add(script.group);
			console.warn(
				`[loadGroups] Script "${script.id}" references unknown group "${script.group}" — treating as ungrouped`,
			);
		}
	}

	// ── 4. For each group: resolve members, validate, generate runner ──────────
	for (const group of groups) {
		// Collect member scripts for this group (only known group IDs)
		const members = scripts.filter((s) => s.group === group.id);

		if (members.length === 0) {
			console.warn(
				`[loadGroups] Group "${group.id}" has no valid member scripts — skipping runner generation`,
			);
			continue;
		}

		// Platform constraint: all members must share the same platform
		const platforms = new Set(members.map((m) => m.platform));
		if (platforms.size > 1) {
			throw new Error(
				`[loadGroups] Group "${group.id}" has members spanning multiple platforms: ${[...platforms].join(", ")}. All scripts in a group must share the same platform.`,
			);
		}

		// Sort members: ascending groupOrder, then id as tiebreaker
		const sortedMembers = [...members].sort(compareMemberScripts);

		// Determine extension from first member's runCommand
		const ext = runnerExtension(sortedMembers[0]);

		// Determine platform folder prefix from first member's id
		const platformPrefix = platformPrefixFromId(sortedMembers[0].id);

		// Build runner content
		const runnerContent =
			ext === ".ps1"
				? buildPs1Runner(group, sortedMembers)
				: buildBashRunner(group, sortedMembers);

		// Write runner to scripts/<platform-prefix>/<group-id>/run-all.{sh,ps1}
		const runnerPath = join(
			scriptsRootPath,
			platformPrefix,
			group.id,
			`run-all${ext}`,
		);

		try {
			await writeFile(runnerPath, runnerContent);
		} catch (err) {
			throw new Error(
				`[loadGroups] Failed to write runner script for group "${group.id}" to "${runnerPath}": ${(err as Error).message}`,
				{ cause: err },
			);
		}
	}

	return groups;
}
