#!/bin/bash
set -euo pipefail

# Runner script for group: Dev Box
# Generated by Scriptor — do not edit by hand.

echo "[1/6] Install GitHub CLI..."
curl -fsSL "https://raw.githubusercontent.com/beolson/Scriptor/main/scripts/linux/debian-13-x64/install-github-cli.sh" | bash
echo "[2/6] Install .NET 10 SDK..."
curl -fsSL "https://raw.githubusercontent.com/beolson/Scriptor/main/scripts/linux/debian-13-x64/install-dotnet.sh" | bash
echo "[3/6] Install Bun..."
curl -fsSL "https://raw.githubusercontent.com/beolson/Scriptor/main/scripts/linux/debian-13-x64/install-bun.sh" | bash
echo "[4/6] Install Go..."
curl -fsSL "https://raw.githubusercontent.com/beolson/Scriptor/main/scripts/linux/debian-13-x64/install-go.sh" | bash
echo "[5/6] Install uv (Python Package Manager)..."
curl -fsSL "https://raw.githubusercontent.com/beolson/Scriptor/main/scripts/linux/debian-13-x64/install-uv.sh" | bash
echo "[6/6] Install Azure CLI and Azure Developer CLI..."
curl -fsSL "https://raw.githubusercontent.com/beolson/Scriptor/main/scripts/linux/debian-13-x64/install-azure-cli.sh" | bash

echo "All 6 script(s) complete."