#!/bin/bash
set -euo pipefail

# Runner script for group: Fixture Group
# Generated by Scriptor — do not edit by hand.

echo "[1/2] Fixture Install curl..."
curl -fsSL "https://raw.githubusercontent.com/beolson/Scriptor/main/scripts/linux/ubuntu-24.04-x64/fixture-install-curl.sh" | bash
echo "[2/2] Fixture Setup Dev..."
curl -fsSL "https://raw.githubusercontent.com/beolson/Scriptor/main/scripts/linux/ubuntu-24.04-x64/fixture-setup-dev.sh" | bash

echo "All 2 script(s) complete."